pull_request_rules:
  - name: Automatic merge when all status checks pass
    conditions:
      - status-success=security/snyk (coderbyheart)
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
        bot_account: coderbyheart
      label:
        add:
          - mergify
      rebase:
        bot_account: coderbyheart
  - name: Automatically approve trusted service PRs
    conditions:
      - author~=^(snyk-bot|dependabot\[bot\]|renovate\[bot\])$
    actions:
      review:
        message: Automatically approved because PR is by a trusted service
