sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_install:
  - npm i -g npm@^2.0.0
script:
  - make build
after_success:
  - cd build
  - git init
  - git config user.name "Travis CI"
  - git config user.email "github@coderbyheart.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/coderbyheart/coderbyheart.com.git" master:gh-pages > /dev/null 2>&1
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
