language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js: '8'
addons:
  apt:
    packages:
    - python-pip
before_install:
- pip install --user s3cmd
before_script:
- npm prune
script:
- npm run lint
after_success:
- npm run semantic-release
- ENVIRONMENT=production make build
- ENVIRONMENT=production make deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
