language: node_js
notifications:
  email: false
node_js: '12'
addons:
  apt:
    packages:
    - python-pip
before_install:
- pip install --user s3cmd
before_script:
- npm prune
script:
- npm run lint
after_success:
- npm i --no-save semantic-release@next
- npx semantic-release
- ENVIRONMENT=production make build
- ENVIRONMENT=production make deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
