name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Export to-be released version
        run: |
          npx semantic-release --dry-run > semantic-release.out
          echo "RELEASE_VERSION=$(cat semantic-release.out | grep -i 'the next release version is' | awk '{print $11}')" >> $GITHUB_ENV
          cat semantic-release.out

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Build
        env:
          VERSION: ${{ env.RELEASE_VERSION }}
          PHOTOS_BUCKET_NAME: photos.coderbyheart
          PHOTOS_CDN_ENDPOINT: https://7w7z6ydf2htamqdsm6nbxm7sma0nkltc.lambda-url.eu-central-1.on.aws/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
        run: npm run build

      - name: Run smoke test
        run: npm run test:e2e

      - name: Save version
        if: env.RELEASE_VERSION !=  ''
        run: |
          mkdir -p ./dist/client/.well-known
          echo "${{ env.RELEASE_VERSION }}" > ./dist/client/.well-known/release

      - name: Upload dist/client artifact
        if: env.RELEASE_VERSION !=  ''
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist-client
          path: ./dist/client
          retention-days: 7

      - name: Semantic release
        if: env.RELEASE_VERSION !=  ''
        id: semantic-release
        run: npx semantic-release
