name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Build
        env:
          PHOTOS_BUCKET_NAME: photos.coderbyheart
          PHOTOS_CDN_ENDPOINT: https://7w7z6ydf2htamqdsm6nbxm7sma0nkltc.lambda-url.eu-central-1.on.aws/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_CONTENT_API_TOKEN:
            ${{ secrets.CONTENTFUL_CONTENT_API_TOKEN }}
        run: npm run build

      - name: Run smoke test
        run: npm run test:e2e

      - name: Semantic release
        id: semantic-release
        run: npx semantic-release
